---
title: "STAT331 Data Visualizations and Dashboards - Assignment 4"
author: "Andrew Sparkes"
date: "2025-10-23"
output: html_document
---

## Assignment 4


The data provided has outlays from the federal spending, organized by state.
The second dataset has state populations.

Generate a geographic visualization that shows per capita federal expenditures.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackages}
library(tidyverse)
library(magrittr) # for %>%
library(ggplot2) # mpg dataset and plotting
library(reticulate) # for calling python
library(tigris) # for states data
library(sf) # simple features
library(ggrepel) # for repelling labels off of one another
library(scales) # label_comma
```

```{r settings}
options(tigris_use_cache = TRUE)
```

```{r loadfile}
pop_data_path = "State Populations Data.xlsx"
spending_data_path = "State Awards 2025.xlsx"


spending_data <- readxl::read_excel(spending_data_path, skip= 2) |>
  rename(State = 'State or Territory Name') |>
  select(State, 'Award Amount') |>
  mutate(State = str_replace(State, "\\([^()]*\\)", "")) |>
  mutate(State = str_trim(State))


pop_data <- readxl::read_excel(pop_data_path, skip = 5) |>
  select(1, 2) |> # select State and Pop
  rename(State = ...1, Pop = `July 1, 2024 (est.)`) |>
  mutate(State = str_replace(State, "\\([^()]*\\)", "")) |>
  mutate(State = str_trim(State))
```


```{r}
# joining on state name, so that population data is mapped to awards data
spending_and_pop_data <- left_join(spending_data, pop_data, by = join_by(State))
```

```{r}
# use tigris to do the left join with the shapes
spending_and_pop_with_shapes <- left_join(tigris::states(), spending_and_pop_data, by = join_by(NAME == State))
```

```{r filter_and_prune}
data_to_plot_w_geo <- spending_and_pop_with_shapes |>
  mutate(`Pop` = as.numeric(`Pop`), `Award Amount` = as.numeric(`Award Amount`)) |> # numeric conversion
  filter(!(STUSPS %in% c("HI", "AK", "AS", "GU", "VI", "PR", "MP"))) # remove Hawaii, Alaska, Guam, etc for now

# removing observations with NA values, may revert this later...
data_to_plot_w_geo <- na.omit(data_to_plot_w_geo)
```


```{r plotting_the_stuff, fig.width=10, fig.height=7}
ploot <- data_to_plot_w_geo |> 
  ggplot() + 
  geom_sf(aes(geometry = geometry,
              fill = log(`Award Amount` / `Pop`))) +
  geom_label_repel(aes(geometry = geometry),
                   data = data_to_plot_w_geo,
                   stat = "sf_coordinates",
                   label = data_to_plot_w_geo$STUSPS) +
  labs(x = "Longitude",
       y = "Latitude") +
  theme_classic() +
  scale_fill_viridis_c(
    option = "mako",
    name = "Log Scale of Award/Population"
  ) +
  guides(
    fill = guide_colourbar(
      title.position = "top", # Position the title above the bar
      title.hjust = 0.5,      # Center the title
    )
  )
ploot
```
